export const recipes = [
  {
    id: 1,
    title: "Queso untable de Kéfir Fácil",
    ingredients: [
      "1 litro de leche",
      "2 cucharadas de gránulos de kéfir",
      "1/4 cucharadita de sal no yodada",
    ],
    preparation: [
      "1 Combina la leche y los gránulos de kéfir, y deja que la mezcla se fermente a temperatura ambiente durante 12-24 horas.",
      "2 Retira los gránulos y permite que la leche fermentada repose durante otras 12-24 horas hasta que se separe en cuajada y suero.",
      "3 Cubre un colador con dos capas de gasa fina y vierte suavemente el kéfir cuajado. Deja que escurra durante 30 minutos, recogiendo el nutritivo suero si lo deseas.",
      "4 Ata la gasa en forma de bola y cuélgala para que escurra durante 4-8 horas adicionales.",
      "5 Transfiere el suave queso de kéfir a un tazón o recipiente, y mezcla la sal y cualquier saborizante deseado.",
      "6 Guarda el queso de kéfir en un recipiente hermético en el refrigerador hasta por 2 semanas, teniendo en cuenta que continuará fermentando y volviéndose más ácido con el tiempo. ¡Disfruta!",
    ],
    details: "",
    images: ["/blog/queso_kefir.jpeg"],
  },
  {
    id: 2,
    title: "Yakult de Suero de Kéfir",
    ingredients: [
      "1 taza de suero de kéfir",
      "1 cucharada de azúcar",
      "1/4 cucharadita de esencia de vainilla",
    ],
    preparation: [
      "1 Combina el suero de kéfir, el azúcar y la esencia de vainilla en un tazón.",
      "2 Mezcla hasta que el azúcar se disuelva por completo.",
      "3 Vierte la mezcla en botellas pequeñas y sella herméticamente.",
      "4 Deja fermentar a temperatura ambiente durante 12-24 horas, o hasta que el yakult esté ligeramente espeso y burbujeante.",
      "5 Refrigera el yakult durante al menos 4 horas antes de servir.",
      "6 Disfruta de una bebida refrescante y probiótica hecha en casa.",
    ],
    details: "",
    images: ["/blog/yakult_kefir.jpg"],
  },
  {
    id: 3,
    title: "Batido de Kéfir y Frutas",
    ingredients: [
      "1 taza de kéfir",
      "1/2 taza de frutas frescas",
      "1 cucharada de miel",
      "1/2 cucharadita de esencia de vainilla",
    ],
    preparation: [
      "1 Combina el kéfir, las frutas, la miel y la esencia de vainilla en una licuadora.",
      "2 Mezcla hasta obtener una consistencia suave y homogénea.",
      "3 Sirve el batido en un vaso y decora con frutas frescas adicionales si lo deseas.",
      "4 Disfruta de un batido refrescante y nutritivo, perfecto para el desayuno o la merienda.",
    ],
    details: "",
    images: ["/blog/kefir_smoothie.jpeg"],
  },
  {
    id: 4,
    title: "Panqueques de Kéfir con Miel",
    ingredients: [
      "1 taza de harina",
      "1/2 taza de kéfir",
      "1 huevo",
      "1 cucharadita de polvo de hornear",
      "1 cucharada de miel",
    ],
    preparation: [
      "1 Combina la harina, el kéfir, el huevo, el polvo de hornear y la miel en un tazón.",
      "2 Mezcla hasta obtener una masa suave y homogénea.",
      "3 Calienta una sartén a fuego medio y vierte un poco de masa para formar los panqueques.",
      "4 Cocina los panqueques durante 2-3 minutos por cada lado, hasta que estén dorados y esponjosos.",
      "5 Sirve los panqueques de kéfir con miel y disfruta de un desayuno delicioso y nutritivo.",
    ],
    details: "",
    images: ["/blog/kefir_pancakes.jpg"],
  },
];
