const cities = [
  {
    id: 1,
    state: "Estado de México",
    image: "/groups/estadodemexico.jpg",
    locations: [
      {
        name: "San Cristóbal Ecatepec",
        link: "https://chat.whatsapp.com/IL4ZVCqLep19HTzgdq3GcM",
      },
      {
        name: "Ciudad Nezahualcóyotl",
        link: "https://chat.whatsapp.com/Hgga7aBx14zFdLx9tqlM2G",
      },
      {
        name: "Naucalpan de Juárez",
        link: "https://chat.whatsapp.com/C87tf9rBtjt1v6tEyLYsw8",
      },
      {
        name: "Ciudad de Tlalnepantla",
        link: "https://chat.whatsapp.com/HzHoTnF2w0LIT6jXIVxVqa",
      },
      {
        name: "Chimalhuacán",
        link: "https://chat.whatsapp.com/H3fxueycSfKAWlcxpThWb9",
      },
      {
        name: "Toluca de Lerdo",
        link: "https://chat.whatsapp.com/EjhEkr87bHF5xy0etRwjcK",
      },
      {
        name: "Ciudad López Mateos",
        link: "https://chat.whatsapp.com/L4xlh3CR77W1FqIR7oxXbV",
      },
      {
        name: "Cuautitlán Izcalli",
        link: "https://chat.whatsapp.com/L0WXuby2uFNHy6nEc4Fp7e",
      },
      {
        name: "Xico",
        link: "https://chat.whatsapp.com/EQDCpFq71fRDMfSrzDffUt",
      },
      {
        name: "Ixtapaluca",
        link: "https://chat.whatsapp.com/DCOByj9y8nHETNr6dX1UdN",
      },
      {
        name: "San Francisco Coacalco",
        link: "https://chat.whatsapp.com/LPJPGI9hte35UJOmPjfe73",
      },
      {
        name: "Ciudad Nicolás Romero",
        link: "https://chat.whatsapp.com/Iv197zNWrMk8fQkZb6P5kb",
      },
      {
        name: "Ojo de Agua",
        link: "https://chat.whatsapp.com/Bpyh8hmtjuiFX0yUtGNtK2",
      },
      {
        name: "Buenavista",
        link: "https://chat.whatsapp.com/HZnUQgGiUop48QudB8pypF",
      },
      {
        name: "San Pablo de las Salinas",
        link: "https://chat.whatsapp.com/EGt4aNkGN9C5UzhEelBNgW",
      },
      {
        name: "Chicoloapan de Juárez",
        link: "https://chat.whatsapp.com/Hb6L1PjZc5l0zXdD7oAeyW",
      },
      {
        name: "Chalco de Díaz Covarrubias",
        link: "https://chat.whatsapp.com/EV7s6mZjg5dJl128QaWgUo",
      },
      {
        name: "Naucalpan de Juárez (Interlomas)",
        link: "https://chat.whatsapp.com/C7nXiouxIsZ1rx9DhZzxmG",
      },
      {
        name: "Cuautitlán",
        link: "https://chat.whatsapp.com/DldiSbMJ7VNGPdNlv3Ukiy",
      },
      // { name: "Texcoco de Mora", link: "" },
      // { name: "Tepexpan", link: "" },
      // { name: "Los Reyes Acaquilpan", link: "" },
      // { name: "Fuentes del Valle", link: "" },
      // { name: "San Mateo Atenco", link: "" },
      // { name: "Tultepec", link: "" },
      // { name: "San Salvador Tizatlalli", link: "" },
      // { name: "San Miguel Zinacantepec", link: "" },
      // { name: "Teoloyucan", link: "" },
      // { name: "Zumpango de Ocampo", link: "" },
      // { name: "San Buenaventura", link: "" },
      // { name: "Melchor Ocampo", link: "" },
      // { name: "Tepotzotlán", link: "" },
      // { name: "Colonia Santa Teresa", link: "" },
      // { name: "San Jerónimo Cuatro Vientos", link: "" },
      // { name: "Coyotepec", link: "" },
      // { name: "San Martín Azcatepec", link: "" },
      // { name: "San Pablo Autopan", link: "" },
      // { name: "San Isidro", link: "" },
      // { name: "Tultitlán de Mariano Escobedo", link: "" },
      // { name: "Amecameca de Juárez", link: "" },
      // { name: "San José Guadalupe Otzacatipan", link: "" },
      // { name: "Metepec", link: "" },
      // { name: "San Francisco Acuautla", link: "" },
      // { name: "La Magdalena Atlicpac", link: "" },
      // { name: "San Jerónimo Chicahualco", link: "" },
      // { name: "Ocoyoacac", link: "" },
      // { name: "Tejupilco", link: "" },
      // { name: "Valle de Bravo", link: "" },
      // { name: "Emiliano Zapata (La Paz)", link: "" },
      // { name: "San Francisco Coaxusco", link: "" },
    ],
  },
  {
    id: 2,
    state: "Ciudad de México",
    image: "/groups/ciudaddemexico.png",
    locations: [
      {
        name: "Milpa Alta",
        link: "https://chat.whatsapp.com/ILsiFqmd4NA3ySHkOKnKKJ",
      },
      {
        name: "Cuajimalpa de Morelos",
        link: "https://chat.whatsapp.com/GkcmtmiZkM6AavlkoAEo4X",
      },
      {
        name: "La Magdalena Contreras",
        link: "https://chat.whatsapp.com/E5Nrco3IVxe0HZFZiKnQii",
      },
      {
        name: "Tláhuac",
        link: "https://chat.whatsapp.com/FgiHdLF5SfI827iTiJl4Pp",
      },
      {
        name: "Iztacalco",
        link: "https://chat.whatsapp.com/J4qVh7R5UG23q68aRa1mS2",
      },
      {
        name: "Miguel Hidalgo",
        link: "https://chat.whatsapp.com/Ip4LW81k4PNDiW7Sh5tKtj",
      },
      {
        name: "Azcapotzalco",
        link: "https://chat.whatsapp.com/LbowokB15Mn1KXybO68jMD",
      },
      {
        name: "Benito Juárez",
        link: "https://chat.whatsapp.com/G5pZWD0WhacIfKtbBc3JO8",
      },
      {
        name: "Xochimilco",
        link: "https://chat.whatsapp.com/HrhWIU3Qu5H6uMJtKLwGqC",
      },
      {
        name: "Venustiano Carranza",
        link: "https://chat.whatsapp.com/GyC5NXkxDaKFymBX3enOS2",
      },
      {
        name: "Cuauhtémoc",
        link: "https://chat.whatsapp.com/K0RTOlcWExTFjY2WlVxckV",
      },
      {
        name: "Coyoacán",
        link: "https://chat.whatsapp.com/LBbhMDyy5nb07H0UXSnb2R",
      },
      {
        name: "Tlalpan",
        link: "https://chat.whatsapp.com/IXoVYgjWt6dDDwPweNyvwF",
      },
      {
        name: "Álvaro Obregón",
        link: "https://chat.whatsapp.com/FJydLoJHDkeGzPMxU0pZcg",
      },
      {
        name: "Gustavo A. Madero",
        link: "https://chat.whatsapp.com/GeH84Hty6BRIeNFt6aJQg4",
      },
      {
        name: "Iztapalapa",
        link: "https://chat.whatsapp.com/Cvy8QZz808ZIPhlCc3AY0R",
      },
    ],
  },
  {
    id: 3,
    state: "Jalisco",
    image: "/groups/jalisco.jpg",
    locations: [
      {
        name: "Guadalajara",
        link: "https://chat.whatsapp.com/Juniokgch9EJdhKVVfuBc9",
      },
      {
        name: "Zapopan",
        link: "https://chat.whatsapp.com/BfOueHmeduNHW1Fu8l713J",
      },
      {
        name: "Tlaquepaque",
        link: "https://chat.whatsapp.com/ERAl0AsqQu48GtrTqcBWfH",
      },
      {
        name: "Tonalá",
        link: "https://chat.whatsapp.com/FsZfYcWUGtW74DOjdcFly8",
      },
      // { name: "Puerto Vallarta", link: "" },
      {
        name: "Tlajomulco de Zúñiga",
        link: "https://chat.whatsapp.com/GLIqYBtqdYa6YKPWe4XbtR",
      },
      {
        name: "El Salto",
        link: "https://chat.whatsapp.com/ClzSp8vM3Y7Bx3INU6HAOh",
      },
      {
        name: "Tepatitlán de Morelos",
        link: "https://chat.whatsapp.com/GAdIZeaZmYy22NLJWaNAeW",
      },
      {
        name: "Lagos de Moreno",
        link: "https://chat.whatsapp.com/DaHZdVOthwwHEHaxi4dF2g",
      },
      {
        name: "Ocotlán",
        link: "https://chat.whatsapp.com/FhlLMS81XCCDSSJSZNgqmf",
      },
      {
        name: "Arandas",
        link: "https://chat.whatsapp.com/IFbSq8l7XnxCaHg3PYtrIG",
      },
      {
        name: "Atotonilco el Alto",
        link: "https://chat.whatsapp.com/KY2QsaADFhb2P08A9RAstg",
      },
      {
        name: "Zapotlanejo",
        link: "https://chat.whatsapp.com/E81CWMTp97I1e18Qsh1PdK",
      },
      {
        name: "San Juan de los Lagos",
        link: "https://chat.whatsapp.com/KCk9d0FFxv8Em4BGPfCZje",
      },
    ],
  },
  {
    id: 4,
    state: "Veracruz",
    image: "/groups/veracruz.jpg",
    locations: [
      {
        name: "Veracruz",
        link: "https://chat.whatsapp.com/DzRV0BGPd4w95QqDVK52CK",
      },
      {
        name: "Xalapa",
        link: "https://chat.whatsapp.com/DXbOeYFiQp55rWlg5n3AsM",
      },
      {
        name: "Coatzacoalcos",
        link: "https://chat.whatsapp.com/JFL2urYIOYoJCeJcWQDd5z",
      },
      {
        name: "Poza Rica",
        link: "https://chat.whatsapp.com/I3j87MevhFWLksqbn9diKO",
      },
      {
        name: "Córdoba",
        link: "https://chat.whatsapp.com/J5oSdQtisRLBF989zKhpc9",
      },
      {
        name: "Orizaba",
        link: "https://chat.whatsapp.com/JG5tgWxRwtr371kwRfkDqn",
      },
      {
        name: "Minatitlán",
        link: "https://chat.whatsapp.com/DXbOeYFiQp55rWlg5n3AsM",
      },
      // { name: "Boca del Río", link: "" },
      // { name: "San Andrés Tuxtla", link: "" },
      // { name: "Martínez de la Torre", link: "" },
      // { name: "Tuxpan", link: "" },
      // { name: "Papantla", link: "" },
      // { name: "Cosamaloapan", link: "" },
      // { name: "Pánuco", link: "" },
      // { name: "Álamo", link: "" },
      // { name: "Acayucan", link: "" },
      // { name: "Fortín", link: "" },
      // { name: "Cosoleacaque", link: "" },
      // { name: "Naranjos", link: "" },
      // { name: "Las Choapas", link: "" },
      // { name: "Alvarado", link: "" },
      // { name: "Catemaco", link: "" },
      // { name: "Huatusco", link: "" },
      // { name: "Jáltipan", link: "" },
      // { name: "Juan Rodríguez Clara", link: "" },
      // { name: "La Antigua", link: "" },
      // { name: "Las Vigas de Ramírez", link: "" },
      // { name: "Nautla", link: "" },
      // { name: "Perote", link: "" },
      // { name: "Río Blanco", link: "" },
      // { name: "San Rafael", link: "" },
      // { name: "Santiago Tuxtla", link: "" },
      // { name: "Tantoyuca", link: "" },
      // { name: "Tempoal", link: "" },
      // { name: "Tierra Blanca", link: "" },
      // { name: "Tres Valles", link: "" },
      // { name: "Zongolica", link: "" },
    ],
  },
  {
    id: 5,
    state: "Puebla",
    image: "/groups/puebla.jpg",
    locations: [
      {
        name: "Puebla",
        link: "https://chat.whatsapp.com/JwObcpeReuRDVtTwgLiiEG",
      },
      {
        name: "Tehuacán",
        link: "https://chat.whatsapp.com/H1EQnIjK7LE8yR7MpnFUu9",
      },
      { name: "San Martín Texmelucan", link: "" },
      { name: "Cholula", link: "" },
      {
        name: "Atlixco",
        link: "https://chat.whatsapp.com/GfeLORrzPzj877OGGq9q6k",
      },
      // { name: "Teziutlán", link: "" },
      {
        name: "Huauchinango",
        link: "https://chat.whatsapp.com/Giedm9idimT0N3TesDIDqr",
      },
      {
        name: "Izúcar de Matamoros",
        link: "https://chat.whatsapp.com/ByrXTp2jYrqGPPoNiXRxxs",
      },
      {
        name: "Acatlán de Osorio",
        link: "https://chat.whatsapp.com/J05OPv39psQ6WHgFXeD1Kz",
      },
      {
        name: "Tecamachalco",
        link: "https://chat.whatsapp.com/Jx1QjmutrGaLlNjXbudM8T",
      },
      {
        name: "Xicotepec",
        link: "https://chat.whatsapp.com/DOi6DKj2aePBPOu9npfIRp",
      },
      {
        name: "Zacatlán",
        link: "https://chat.whatsapp.com/IGuIFi2DChI0tZax24yOV8",
      },
      {
        name: "Tlatlauquitepec",
        link: "https://chat.whatsapp.com/Jp2dKBeqf9ZC67Go0WF61T",
      },
      {
        name: "Chignahuapan",
        link: "https://chat.whatsapp.com/EzG7vme2CsiCBiWSM3lXy6",
      },
      {
        name: "Tepeaca",
        link: "https://chat.whatsapp.com/DbRKBGwpW1lG73HoTyHpcW",
      },
      // { name: "Tepeyahualco", link: "" },
      // { name: "Tepexi de Rodríguez", link: "" },
      //     { name: "Tetela de Ocampo", link: "" },
      //     { name: "Tlachichuca", link: "" },
      //     { name: "Tlapanalá", link: "" },
      //     { name: "Tlaxco", link: "" },
      //     { name: "Tochimilco", link: "" },
      //     { name: "Tzicatlacoyan", link: "" },
      //     { name: "Venustiano Carranza", link: "" },
      //     { name: "Vicente Guerrero", link: "" },
      //     { name: "Xayacatlán de Bravo", link: "" },
      //     { name: "Xicotepec de Juárez", link: "" },
      //     { name: "Xicotlán", link: "" },
      //     { name: "Xiutetelco", link: "" },
      //     { name: "Xochiapulco", link: "" },
      //     { name: "Xochitlán de Vicente Suárez", link: "" },
      //     { name: "Xochitlán Todos Santos", link: "" },
      //     { name: "Yaonáhuac", link: "" },
      //     { name: "Yehualtepec", link: "" },
      //     { name: "Zacapala", link: "" },
      //     { name: "Zacapoaxtla", link: "" },
      //     { name: "Zacatlán", link: "" },
      //     { name: "Zapotitlán", link: "" },
      //     { name: "Zapotitlán de Méndez", link: "" },
      //     { name: "Zaragoza", link: "" },
      //     { name: "Zautla", link: "" },
      //     { name: "Zihuateutla", link: "" },
      //     { name: "Zinacatepec", link: "" },
      //     { name: "Zongozotla", link: "" },
      //     { name: "Zoquiapan", link: "" },
      //     { name: "Zoquitlán", link: "" },
      //     { name: "Zacatlán", link: "" },
      //     { name: "Zapotitlán", link: "" },
      //     { name: "Zapotitlán de Méndez", link: "" },
      //     { name: "Zaragoza", link: "" },
      //     { name: "Zautla", link: "" },
      //     { name: "Zihuateutla", link: "" },
      //     { name: "Zinacatepec", link: "" },
      //     { name: "Zongozotla", link: "" },
      //     { name: "Zoquiapan", link: "" },
      //     { name: "Zoquitlán", link: "" },
    ],
  },
  {
    id: 6,
    state: "Nuevo León",
    image: "/groups/nuevoleon.jpg",
    locations: [
      {
        name: "Monterrey",
        link: "https://chat.whatsapp.com/JB4jHReKS698JDZILvsSvM",
      },
      {
        name: "Guadalupe",
        link: "https://chat.whatsapp.com/DmXvL6dgZNr9W0WGEQ9FSy",
      },
      {
        name: "San Nicolás de los Garza",
        link: "https://chat.whatsapp.com/LdFaEfiL958HEDhBUalOwF",
      },
      {
        name: "Apodaca",
        link: "https://chat.whatsapp.com/LvudkOgrH0F09DIQhHGdCK",
      },
      {
        name: "General Escobedo",
        link: "https://chat.whatsapp.com/CXWfuujQX94LXIE0hjA9V4",
      },
      {
        name: "Santa Catarina",
        link: "https://chat.whatsapp.com/HKoBSfrFMHzClAtFgyQ7ko",
      },
      // { name: "San Pedro Garza García", link: "" },
      // { name: "Salinas Victoria", link: "" },
      // { name: "Sabinas Hidalgo", link: "" },
      // { name: "Cadereyta Jiménez", link: "" },
      // { name: "García", link: "" },
      // { name: "Linares", link: "" },
      //     { name: "Montemorelos", link: "" },
      //     { name: "Allende", link: "" },
      //     { name: "Hidalgo", link: "" },
      //     { name: "Ciénega de Flores", link: "" },
      //     { name: "El Carmen", link: "" },
      //     { name: "Juárez", link: "" },
      //     { name: "Pesquería", link: "" },
      //     { name: "Doctor González", link: "" },
      //     { name: "Los Ramones", link: "" },
      //     { name: "Marín", link: "" },
      //     { name: "Abasolo", link: "" },
      //     { name: "Anáhuac", link: "" },
      //     { name: "Aramberri", link: "" },
      //     { name: "Bustamante", link: "" },
      //     { name: "Cerralvo", link: "" },
      //     { name: "China", link: "" },
      //     { name: "Ciénega de Flores", link: "" },
      //     { name: "Doctor Arroyo", link: "" },
      //     { name: "Doctor Coss", link: "" },
      //     { name: "Doctor González", link: "" },
      //     { name: "El Carmen", link: "" },
      //     { name: "Galeana", link: "" },
      //     { name: "García", link: "" },
      //     { name: "General Bravo", link: "" },
      //     { name: "General Escobedo", link: "" },
      //     { name: "General Terán", link: "" },
      //     { name: "General Treviño", link: "" },
      //     { name: "General Zaragoza", link: "" },
      //     { name: "General Zuazua", link: "" },
      //     { name: "Guadalupe", link: "" },
      //     { name: "Hidalgo", link: "" },
      //     { name: "Higueras", link: "" },
      //     { name: "Hualahuises", link: "" },
      //     { name: "Iturbide", link: "" },
      //     { name: "Juárez", link: "" },
      //     { name: "Lampazos de Naranjo", link: "" },
      //     { name: "Linares", link: "" },
      //     { name: "Los Aldamas", link: "" },
      //     { name: "Los Herreras", link: "" },
      //     { name: "Los Ramones", link: "" },
      //     { name: "Marín", link: "" },
      //     { name: "Melchor Ocampo", link: "" },
      //     { name: "Mier y Noriega", link: "" },
      //     { name: "Mina", link: "" },
      //     { name: "Montemorelos", link: "" },
      //     { name: "Monterrey", link: "" },
      //     { name: "Parás", link: "" },
      //     { name: "Pesquería", link: "" },
      //     { name: "Rayones", link: "" },
      //     { name: "Sabinas Hidalgo", link: "" },
      //     { name: "Salinas Victoria", link: "" },
      //     { name: "San Nicolás de los Garza", link: "" },
      //     { name: "San Pedro Garza García", link: "" },
      //     { name: "Santa Catarina", link: "" },
      //     { name: "Santiago", link: "" },
      //     { name: "Vallecillo", link: "" },
      //     { name: "Villaldama", link: "" },
    ],
  },
  {
    id: 7,
    state: "Guanajuato",
    image: "/groups/guanajuato.jpg",
    locations: [
      {
        name: "Moroleón",
        link: "https://chat.whatsapp.com/K1KRdKzkFKV2kOCZ4UiTp8",
      },
      {
        name: "Jerécuaro",
        link: "https://chat.whatsapp.com/LsSxF7TwkHs8G7agRJGT3a",
      },
      {
        name: "Uriangato",
        link: "https://chat.whatsapp.com/C42l9AWeIGc69XQFIsmeeL",
      },
      {
        name: "Apaseo el Alto",
        link: "https://chat.whatsapp.com/Ee6eDS02f8LLIa7gAsDqar",
      },
      {
        name: "Romita",
        link: "https://chat.whatsapp.com/GBke4mR3ZZkLZyPNJCujIU",
      },
      {
        name: "Villagrán",
        link: "https://chat.whatsapp.com/K6l8uFADtSBA4WxSLJVwDn",
      },
      {
        name: "Yuriria",
        link: "https://chat.whatsapp.com/ENM6LvtVVE40K92mMnmHQh",
      },
      {
        name: "Comonfort",
        link: "https://chat.whatsapp.com/H8mg4EF1slGGGJIYq1qNTO",
      },
      // { name: "Santa Cruz de Juventino Rosas", link: "https://chat.whatsapp.com/F58dVxvbOVeCQTytg1b1yn" },
      // { name: "Purísima del Rincón", link: "" },
      // { name: "San José Iturbide", link: "" },
      // { name: "Abasolo", link: "" },
      //     { name: "Salvatierra", link: "" },
      //     { name: "Cortazar", link: "" },
      //     { name: "Acámbaro", link: "" },
      //     { name: "Apaseo el Grande", link: "" },
      //     { name: "San Felipe", link: "" },
      //     { name: "San Luis de la Paz", link: "" },
      //     { name: "San Francisco del Rincón", link: "" },
      //     { name: "Valle de Santiago", link: "" },
      //     { name: "Pénjamo", link: "" },
      //     { name: "Dolores Hidalgo Cuna de la Independencia Nacional", link: "" },
      //     { name: "San Miguel de Allende", link: "" },
      //     { name: "Guanajuato", link: "" },
      //     { name: "Silao de la Victoria", link: "" },
      //     { name: "Salamanca", link: "" },
      //     { name: "Celaya", link: "" },
      //     { name: "Irapuato", link: "" },
      //     { name: "León", link: "" },
    ],
  },
  {
    id: 8,
    state: "Chihuahua",
    image: "/groups/chihuahua.jpg",
    locations: [
      {
        name: "Ciudad Juárez",
        link: "https://chat.whatsapp.com/KYGaycvIW42DiQanJObH25",
      },
      {
        name: "Chihuahua",
        link: "https://chat.whatsapp.com/JH4SUXPrJ0zGifVmGjA44y",
      },
      {
        name: "Delicias",
        link: "https://chat.whatsapp.com/GUPEjSNZTmiLPSNZQFXHxB",
      },
      {
        name: "Cuauhtémoc",
        link: "https://chat.whatsapp.com/J09xRHrRIj71DPU8TwfNB6",
      },
      {
        name: "Hidalgo del Parral",
        link: "https://chat.whatsapp.com/BhzlWo4aVPE1AuN0RtJoq5",
      },
      {
        name: "Ojinaga",
        link: "https://chat.whatsapp.com/EstuXJkLA237M89GQ4PdkO",
      },
      {
        name: "Nuevo Casas Grandes",
        link: "https://chat.whatsapp.com/FfoJATDpvvTJEXR1L0vzAD",
      },
      {
        name: "Camargo",
        link: "https://chat.whatsapp.com/LWLQYAt2RoqAS7rzun9Dt7",
      },
      {
        name: "Jiménez",
        link: "https://chat.whatsapp.com/IV4c5L6ojsB0QEp8NmA2jt",
      },
      //     { name: "Meoqui", link: "" },
      //     { name: "Guerrero", link: "" },
      //     { name: "Ascensión", link: "" },
      //     { name: "Janos", link: "" },
      //     { name: "Galeana", link: "" },
      //     { name: "Buenaventura", link: "" },
      //     { name: "Ignacio Zaragoza", link: "" },
      //     { name: "Praxedis G. Guerrero", link: "" },
      //     { name: "Ahumada", link: "" },
      //     { name: "Coyame del Sotol", link: "" },
      //     { name: "Villa Ahumada", link: "" },
      //     { name: "Rosales", link: "" },
      //     { name: "Saucillo", link: "" },
      //     { name: "Santa Bárbara", link: "" },
      //     { name: "Guadalupe", link: "" },
      //     { name: "Coronado", link: "" },
      //     { name: "Valentín Gómez Farías", link: "" },
      //     { name: "San Francisco de Borja", link: "" },
      //     { name: "San Francisco de Conchos", link: "" },
      //     { name: "Bachíniva", link: "" },
      //     { name: "Balleza", link: "" },
      //     { name: "Batopilas", link: "" },
      //     { name: "Bocoyna", link: "" },
      //     { name: "Buenaventura", link: "" },
      //     { name: "Camargo", link: "" },
      //     { name: "Carichí", link: "" },
      //     { name: "Casas Grandes", link: "" },
      //     { name: "Coronado", link: "" },
      //     { name: "Coyame del Sotol", link: "" },
      //     { name: "Cuauhtémoc", link: "" },
      //     { name: "Cusihuiriachi", link: "" },
      //     { name: "Delicias", link: "" },
      //     { name: "Dr. Belisario Domínguez", link: "" },
      //     { name: "Galeana", link: "" },
      //     { name: "Gómez Farías", link: "" },
      //     { name: "Gran Morelos", link: "" },
      //     { name: "Guachochi", link: "" },
      //     { name: "Guadalupe", link: "" },
      //     { name: "Guadalupe y Calvo", link: "" },
      //     { name: "Guazapares", link: "" },
      //     { name: "Guerrero", link: "" },
      //     { name: "Hidalgo del Parral", link: "" },
      //     { name: "Ignacio Zaragoza", link: "" },
      //     { name: "Janos", link: "" },
      //     { name: "Jiménez", link: "" },
      //     { name: "Juárez", link: "" },
      //     { name: "Julimes", link: "" },
      //     { name: "López", link: "" },
      //     { name: "Madera", link: "" },
      //     { name: "Maguarichi", link: "" },
      //     { name: "Manuel Benavides", link: "" },
      //     { name: "Matachí", link: "" },
      //     { name: "Matamoros", link: "" },
      //     { name: "Meoqui", link: "" },
      //     { name: "Morelos", link: "" },
      //     { name: "Moris", link: "" },
      //     { name: "Namiquipa", link: "" },
      //     { name: "Nonoava", link: "" },
      //     { name: "Nuevo Casas Grandes", link: "" },
      //     { name: "Ocampo", link: "" },
      //     { name: "Ojinaga", link: "" },
      //     { name: "Praxedis G. Guerrero", link: "" },
    ],
  },
  {
    id: 9,
    state: "Chiapas",
    image: "/groups/chiapas.jpg",
    locations: [
      {
        name: "Tuxtla Gutiérrez",
        link: "https://chat.whatsapp.com/FvGCOcLVzAjJ1T1pprRNuo",
      },
      {
        name: "Tapachula",
        link: "https://chat.whatsapp.com/Lbo4pjNsqn0Hi5QiGLHh3q",
      },
      {
        name: "San Cristóbal de las Casas",
        link: "https://chat.whatsapp.com/HxV9lT3z5iE0OvywoJaT6Z",
      },
      {
        name: "Comitán de Domínguez",
        link: "https://chat.whatsapp.com/CteI3TweAjd0ZHW13xL3rw",
      },
      {
        name: "Palenque",
        link: "https://chat.whatsapp.com/FhCteX2vXz33lXrPzDLW1y",
      },
      {
        name: "Chiapa de Corzo",
        link: "https://chat.whatsapp.com/KDahGDMPGrsCrKN3cWT3zf",
      },
      //     { name: "Villaflores", link: "" },
      //     { name: "Ocosingo", link: "" },
      //     { name: "Tonalá", link: "" },
      //     { name: "Reforma", link: "" },
      //     { name: "Pichucalco", link: "" },
      //     { name: "Cintalapa", link: "" },
      //     { name: "Huixtla", link: "" },
      //     { name: "Motozintla", link: "" },
      //     { name: "Las Margaritas", link: "" },
      //     { name: "Simojovel", link: "" },
      //     { name: "San Fernando", link: "" },
      //     { name: "Mapastepec", link: "" },
      //     { name: "Berriozábal", link: "" },
      //     { name: "Arriaga", link: "" },
      //     { name: "Jiquipilas", link: "" },
      //     { name: "Suchiapa", link: "" },
      //     { name: "Venustiano Carranza", link: "" },
      //     { name: "La Trinitaria", link: "" },
      //     { name: "Frontera Comalapa", link: "" },
      //     { name: "Pijijiapan", link: "" },
      //     { name: "Ocozocoautla de Espinosa", link: "" },
      //     { name: "Tila", link: "" },
      //     { name: "Yajalón", link: "" },
      //     { name: "El Bosque", link: "" },
    ],
  },
  // {
  //   id: 10,
  //   state: "Oaxaca",
  //   image: "/groups/oaxaca.jpg",
  //   locations: [
  //     { name: "Oaxaca de Juárez", link: "" },
  //     { name: "Santa Cruz Xoxocotlán", link: "" },
  //     { name: "San Juan Bautista Tuxtepec", link: "" },
  //     { name: "Salina Cruz", link: "" },
  //     { name: "Juchitán de Zaragoza", link: "" },
  //     { name: "Huajuapan de León", link: "" },
  //     { name: "San Pedro Mixtepec", link: "" },
  //     { name: "San Pedro Pochutla", link: "" },
  //     { name: "Santa Lucía del Camino", link: "" },
  //     { name: "Loma Bonita", link: "" },
  //     { name: "Puerto Escondido", link: "" },
  //     { name: "Miahuatlán de Porfirio Díaz", link: "" },
  //     { name: "Heroica Ciudad de Tlaxiaco", link: "" },
  //     { name: "San Felipe Jalapa de Díaz", link: "" },
  //     { name: "Santo Domingo Tehuantepec", link: "" },
  //     { name: "San Juan Bautista Valle Nacional", link: "" },
  //     { name: "San Pablo Villa de Mitla", link: "" },
  //     { name: "Santa María Huatulco", link: "" },
  //     { name: "Asunción Nochixtlán", link: "" },
  //     { name: "San Pedro Tapanatepec", link: "" },
  //     { name: "San Juan Bautista Lo de Soto", link: "" },
  //     { name: "San Pedro Jicayán", link: "" },
  //     { name: "San Juan Bautista Cuicatlán", link: "" },
  //     { name: "San Pedro y San Pablo Ayutla", link: "" },
  //     { name: "San Juan Bautista Guelache", link: "" },
  //     { name: "San Pedro Amuzgos", link: "" },
  //     { name: "San Juan Bautista Jayacatlán", link: "" },
  //     { name: "San Pedro Cajonos", link: "" },
  //     { name: "San Juan Bautista Tlacoatzintepec", link: "" },
  //     { name: "San Pedro Quiatoni", link: "" },
  //   ],
  // },
  // {
  //   id: 11,
  //   state: "Guerrero",
  //   image: "/groups/guerrero.jpg",
  //   locations: [
  //     { name: "Acapulco de Juárez", link: "" },
  //     { name: "Chilpancingo de los Bravo", link: "" },
  //     { name: "Iguala de la Independencia", link: "" },
  //     { name: "Zihuatanejo de Azueta", link: "" },
  //     { name: "Taxco de Alarcón", link: "" },
  //     { name: "Ciudad Altamirano", link: "" },
  //     { name: "Chilapa de Álvarez", link: "" },
  //     { name: "Tlapa de Comonfort", link: "" },
  //     { name: "Ometepec", link: "" },
  //     { name: "Coyuca de Benítez", link: "" },
  //     { name: "Atoyac de Álvarez", link: "" },
  //     { name: "Tecpan de Galeana", link: "" },
  //     { name: "San Marcos", link: "" },
  //     { name: "Petatlán", link: "" },
  //     { name: "Ayutla de los Libres", link: "" },
  //     { name: "Tixtla de Guerrero", link: "" },
  //     { name: "Pungarabato", link: "" },
  //     { name: "Arcelia", link: "" },
  //     { name: "Igualapa", link: "" },
  //     { name: "Xochistlahuaca", link: "" },
  //     { name: "San Luis Acatlán", link: "" },
  //     { name: "Marquelia", link: "" },
  //     { name: "Copala", link: "" },
  //     { name: "Cuautepec", link: "" },
  //     { name: "Florencio Villarreal", link: "" },
  //     { name: "Cuajinicuilapa", link: "" },
  //     { name: "Tecoanapa", link: "" },
  //     { name: "Metlatónoc", link: "" },
  //     { name: "Alcozauca de Guerrero", link: "" },
  //     { name: "Atlixtac", link: "" },
  //     { name: "Malinaltepec", link: "" },
  //     { name: "Tlacoapa", link: "" },
  //     { name: "Xalpatláhuac", link: "" },
  //     { name: "Zapotitlán Tablas", link: "" },
  //     { name: "Acatepec", link: "" },
  //     { name: "Atlamajalcingo del Monte", link: "" },
  //     { name: "Cochoapa el Grande", link: "" },
  //     { name: "Iliatenco", link: "" },
  //     { name: "José Joaquín de Herrera", link: "" },
  //     { name: "Alpoyeca", link: "" },
  //     { name: "Cualác", link: "" },
  //     { name: "Huamuxtitlán", link: "" },
  //     { name: "Olinalá", link: "" },
  //     { name: "Xochihuehuetlán", link: "" },
  //     { name: "Zitlala", link: "" },
  //     { name: "Ahuacuotzingo", link: "" },
  //     { name: "Mochitlán", link: "" },
  //     { name: "Quechultenango", link: "" },
  //     { name: "Eduardo Neri", link: "" },
  //     { name: "Juan R. Escudero", link: "" },
  //     { name: "Tecoanapa", link: "" },
  //     { name: "Tepecoacuilco de Trujano", link: "" },
  //     { name: "Huitzuco de los Figueroa", link: "" },
  //     { name: "Pilcaya", link: "" },
  //     { name: "Tetipac", link: "" },
  //     { name: "Apaxtla", link: "" },
  //     { name: "Canuto A. Neri", link: "" },
  //     { name: "Cuetzala del Progreso", link: "" },
  //     { name: "General Canuto A. Neri", link: "" },
  //     { name: "Ixcateopan de Cuauhtémoc", link: "" },
  //     { name: "Pedro Ascencio Alquisiras", link: "" },
  //     { name: "Teloloapan", link: "" },
  //     { name: "Cocula", link: "" },
  //     { name: "Copalillo", link: "" },
  //     { name: "Cualac", link: "" },
  //     { name: "Huamuxtitlán", link: "" },
  //     { name: "Olinalá", link: "" },
  //     { name: "Xochihuehuetlán", link: "" },
  //     { name: "Zitlala", link: "" },
  //     { name: "Ahuacuotzingo", link: "" },
  //     { name: "Mochitlán", link: "" },
  //   ],
  // },
  // {
  //   id: 12,
  //   state: "Baja California",
  //   image: "/groups/bajacalifornia.jpg",
  //   locations: [
  //     { name: "Tijuana", link: "" },
  //     { name: "Mexicali", link: "" },
  //     { name: "Ensenada", link: "" },
  //     { name: "Playas de Rosarito", link: "" },
  //     { name: "Tecate", link: "" },
  //     { name: "San Quintín", link: "" },
  //     { name: "San Felipe", link: "" },
  //     { name: "San Luis Río Colorado", link: "" },
  //     { name: "Puerto Peñasco", link: "" },
  //     { name: "González Ortega", link: "" },
  //     { name: "El Porvenir", link: "" },
  //     { name: "El Sauzal", link: "" },
  //     { name: "El Rosario", link: "" },
  //     { name: "El Pípila", link: "" },
  //     { name: "El Papalote", link: "" },
  //     { name: "El Nido", link: "" },
  //     { name: "El Mirador", link: "" },
  //     { name: "El Mármol", link: "" },
  //     { name: "El Manantial", link: "" },
  //     { name: "El Lienzo", link: "" },
  //     { name: "El Hongo", link: "" },
  //     { name: "El Florido", link: "" },
  //     { name: "El Descanso", link: "" },
  //     { name: "El Centinela", link: "" },
  //     { name: "El Choropo", link: "" },
  //     { name: "El Chorro", link: "" },
  //     { name: "El Choyal", link: "" },
  //     { name: "El Ciprés", link: "" },
  //     { name: "El Chaparral", link: "" },
  //     { name: "El Carrizo", link: "" },
  //     { name: "El Cajón", link: "" },
  //     { name: "El Borrego", link: "" },
  //     { name: "El Águila", link: "" },
  //     { name: "El Aguajito", link: "" },
  //     { name: "El Aguaje", link: "" },
  //     { name: "El Álamo", link: "" },
  //   ],
  // },
  // {
  //   id: 13,
  //   state: "Tamaulipas",
  //   image: "/groups/tamaulipas.jpg",
  //   locations: [
  //     { name: "Reynosa", link: "" },
  //     { name: "Matamoros", link: "" },
  //     { name: "Nuevo Laredo", link: "" },
  //     { name: "Ciudad Victoria", link: "" },
  //     { name: "Tampico", link: "" },
  //     { name: "Ciudad Madero", link: "" },
  //     { name: "Altamira", link: "" },
  //     { name: "Ciudad Mante", link: "" },
  //     { name: "San Fernando", link: "" },
  //     { name: "Río Bravo", link: "" },
  //     { name: "Valle Hermoso", link: "" },
  //     { name: "Miguel Alemán", link: "" },
  //     { name: "Gustavo Díaz Ordaz", link: "" },
  //     { name: "Camargo", link: "" },
  //     { name: "Reynosa Díaz", link: "" },
  //     { name: "Hidalgo", link: "" },
  //     { name: "Padilla", link: "" },
  //     { name: "San Carlos", link: "" },
  //     { name: "San Nicolás", link: "" },
  //     { name: "Villagrán", link: "" },
  //     { name: "Mainero", link: "" },
  //     { name: "Abasolo", link: "" },
  //     { name: "Jiménez", link: "" },
  //     { name: "Llera", link: "" },
  //     { name: "González", link: "" },
  //     { name: "Xicoténcatl", link: "" },
  //     { name: "Ocampo", link: "" },
  //     { name: "Antiguo Morelos", link: "" },
  //     { name: "Nuevo Morelos", link: "" },
  //     { name: "El Mante", link: "" },
  //   ],
  // },
  // {
  //   id: 14,
  //   state: "Michoacán",
  //   image: "/groups/michoacan.jpg",
  //   locations: [
  //     { name: "Morelia", link: "" },
  //     { name: "Uruapan", link: "" },
  //     { name: "Zamora", link: "" },
  //     { name: "Lázaro Cárdenas", link: "" },
  //     { name: "Apatzingán", link: "" },
  //     { name: "Zitácuaro", link: "" },
  //     { name: "La Piedad", link: "" },
  //     { name: "Pátzcuaro", link: "" },
  //     { name: "Hidalgo", link: "" },
  //     { name: "Jacona", link: "" },
  //     { name: "Sahuayo", link: "" },
  //     { name: "Los Reyes", link: "" },
  //     { name: "Maravatío", link: "" },
  //     { name: "Puruándiro", link: "" },
  //     { name: "Ciudad Hidalgo", link: "" },
  //     { name: "Tacámbaro", link: "" },
  //     { name: "Zinapécuaro", link: "" },
  //     { name: "Tingüindín", link: "" },
  //     { name: "Tuxpan", link: "" },
  //     { name: "Taretan", link: "" },
  //     { name: "Tingambato", link: "" },
  //     { name: "Tzintzuntzan", link: "" },
  //     { name: "Quiroga", link: "" },
  //     { name: "Paracho", link: "" },
  //     { name: "Ario de Rosales", link: "" },
  //     { name: "Coalcomán", link: "" },
  //     { name: "Huetamo", link: "" },
  //     { name: "Jiquilpan", link: "" },
  //     { name: "Múgica", link: "" },
  //     { name: "Nuevo Parangaricutiro", link: "" },
  //   ],
  // },
  // {
  //   id: 15,
  //   state: "Sinaloa",
  //   image: "/groups/sinaloa.jpg",
  //   locations: [
  //     { name: "Culiacán", link: "" },
  //     { name: "Mazatlán", link: "" },
  //     { name: "Los Mochis", link: "" },
  //     { name: "Guasave", link: "" },
  //     { name: "Navolato", link: "" },
  //     { name: "Escuinapa", link: "" },
  //     { name: "El Rosario", link: "" },
  //     { name: "El Fuerte", link: "" },
  //     { name: "Salvador Alvarado", link: "" },
  //     { name: "Mocorito", link: "" },
  //     { name: "Angostura", link: "" },
  //     { name: "Badiraguato", link: "" },
  //     { name: "Choix", link: "" },
  //     { name: "Concordia", link: "" },
  //     { name: "Cosalá", link: "" },
  //     { name: "San Ignacio", link: "" },
  //     { name: "Sinaloa de Leyva", link: "" },
  //   ],
  // },
];
export default cities;
