export const cities = [
  {
    id: 1,
    state: "Estado de México",
    image: "/groups/estadodemexico.jpg",
    locations: [
      "San Cristóbal Ecatepec",
      "Ciudad Nezahualcóyotl",
      "Naucalpan de Juárez",
      "Ciudad de Tlalnepantla",
      "Chimalhuacán",
      "Toluca de Lerdo",
      "Ciudad López Mateos",
      "Cuautitlán Izcalli",
      "Xico",
      "Ixtapaluca",
      "San Francisco Coacalco",
      "Ciudad Nicolás Romero",
      "Ojo de Agua",
      "Buenavista",
      "San Pablo de las Salinas",
      "Chicoloapan de Juárez",
      "Chalco de Díaz Covarrubias",
      "Naucalpan de Juárez (Interlomas)",
      "Cuautitlán",
      "Texcoco de Mora",
      "Tepexpan",
      "Los Reyes Acaquilpan",
      "Fuentes del Valle",
      "San Mateo Atenco",
      "Tultepec",
      "San Salvador Tizatlalli",
      "San Miguel Zinacantepec",
      "Teoloyucan",
      "Zumpango de Ocampo",
      "San Buenaventura",
      "Melchor Ocampo",
      "Tepotzotlán",
      "Colonia Santa Teresa",
      "San Jerónimo Cuatro Vientos",
      "Coyotepec",
      "San Martín Azcatepec",
      "San Pablo Autopan",
      "San Isidro",
      "Tultitlán de Mariano Escobedo",
      "Amecameca de Juárez",
      "San José Guadalupe Otzacatipan",
      "Metepec",
      "San Francisco Acuautla",
      "La Magdalena Atlicpac",
      "San Jerónimo Chicahualco",
      "Ocoyoacac",
      "Tejupilco",
      "Valle de Bravo",
      "Emiliano Zapata (La Paz)",
      "San Francisco Coaxusco",
    ],
  },
  {
    id: 2,
    state: "Ciudad de México",
    image: "/groups/ciudaddemexico.png",
    locations: [
      "Milpa Alta",
      "Cuajimalpa de Morelos",
      "La Magdalena Contreras",
      "Tláhuac",
      "Iztacalco",
      "Miguel Hidalgo",
      "Azcapotzalco",
      "Benito Juárez",
      "Xochimilco",
      "Venustiano Carranza",
      "Cuauhtémoc",
      "Coyoacán",
      "Tlalpan",
      "Álvaro Obregón",
      "Gustavo A. Madero",
      "Iztapalapa",
    ],
  },
  {
    id: 3,
    state: "Jalisco",
    image: "/groups/jalisco.jpg",
    locations: [
      "Guadalajara",
      "Zapopan",
      "Tlaquepaque",
      "Tonalá",
      "Puerto Vallarta",
      "Tlajomulco de Zúñiga",
      "El Salto",
      "Tepatitlán de Morelos",
      "Lagos de Moreno",
      "Ocotlán",
      "Arandas",
      "Atotonilco el Alto",
      "Zapotlanejo",
      "San Juan de los Lagos",
    ],
  },
  {
    id: 4,
    state: "Veracruz",
    image: "/groups/veracruz.jpg",
    locations: [
      "Veracruz",
      "Xalapa",
      "Coatzacoalcos",
      "Poza Rica",
      "Córdoba",
      "Orizaba",
      "Minatitlán",
      "Boca del Río",
      "San Andrés Tuxtla",
      "Martínez de la Torre",
      "Tuxpan",
      "Papantla",
      "Cosamaloapan",
      "Pánuco",
      "Álamo",
      "Acayucan",
      "Fortín",
      "Cosoleacaque",
      "Naranjos",
      "Las Choapas",
      "Alvarado",
      "Catemaco",
      "Huatusco",
      "Jáltipan",
      "Juan Rodríguez Clara",
      "La Antigua",
      "Las Vigas de Ramírez",
      "Nautla",
      "Perote",
      "Río Blanco",
      "San Rafael",
      "Santiago Tuxtla",
      "Tantoyuca",
      "Tempoal",
      "Tierra Blanca",
      "Tres Valles",
      "Zongolica",
    ],
  },
  {
    id: 5,
    state: "Puebla",
    image: "/groups/puebla.jpg",
    locations: [
      "Puebla",
      "Tehuacán",
      "San Martín Texmelucan",
      "Cholula",
      "Atlixco",
      "Teziutlán",
      "Huauchinango",
      "Izúcar de Matamoros",
      "Acatlán de Osorio",
      "Tecamachalco",
      "Xicotepec",
      "Zacatlán",
      "Tlatlauquitepec",
      "Chignahuapan",
      "Tepeaca",
      "Tepeyahualco",
      "Tepexi de Rodríguez",
      "Tetela de Ocampo",
      "Tlachichuca",
      "Tlapanalá",
      "Tlaxco",
      "Tochimilco",
      "Tzicatlacoyan",
      "Venustiano Carranza",
      "Vicente Guerrero",
      "Xayacatlán de Bravo",
      "Xicotepec de Juárez",
      "Xicotlán",
      "Xiutetelco",
      "Xochiapulco",
      "Xochitlán de Vicente Suárez",
      "Xochitlán Todos Santos",
      "Yaonáhuac",
      "Yehualtepec",
      "Zacapala",
      "Zacapoaxtla",
      "Zacatlán",
      "Zapotitlán",
      "Zapotitlán de Méndez",
      "Zaragoza",
      "Zautla",
      "Zihuateutla",
      "Zinacatepec",
      "Zongozotla",
      "Zoquiapan",
      "Zoquitlán",
      "Zacatlán",
      "Zapotitlán",
      "Zapotitlán de Méndez",
      "Zaragoza",
      "Zautla",
      "Zihuateutla",
      "Zinacatepec",
      "Zongozotla",
      "Zoquiapan",
      "Zoquitlán",
      "Zacatlán",
      "Zapotitlán",
      "Zapotitlán de Méndez",
    ],
  },
  {
    id: 6,
    state: "Nuevo León",
    image: "/groups/nuevoleon.jpg",
    locations: [
      "Monterrey",
      "Guadalupe",
      "San Nicolás de los Garza",
      "Apodaca",
      "General Escobedo",
      "Santa Catarina",
      "San Pedro Garza García",
      "Salinas Victoria",
      "Sabinas Hidalgo",
      "Cadereyta Jiménez",
      "García",
      "Linares",
      "Montemorelos",
      "Allende",
      "Hidalgo",
      "Ciénega de Flores",
      "El Carmen",
      "Juárez",
      "Pesquería",
      "Doctor González",
      "Los Ramones",
      "Marín",
      "Abasolo",
      "Anáhuac",
      "Aramberri",
      "Bustamante",
      "Cerralvo",
      "China",
      "Ciénega de Flores",
      "Doctor Arroyo",
      "Doctor Coss",
      "Doctor González",
      "El Carmen",
      "Galeana",
      "García",
      "General Bravo",
      "General Escobedo",
      "General Terán",
      "General Treviño",
      "General Zaragoza",
      "General Zuazua",
      "Guadalupe",
      "Hidalgo",
      "Higueras",
      "Hualahuises",
      "Iturbide",
      "Juárez",
      "Lampazos de Naranjo",
      "Linares",
      "Los Aldamas",
      "Los Herreras",
      "Los Ramones",
      "Marín",
      "Melchor Ocampo",
      "Mier y Noriega",
      "Mina",
      "Montemorelos",
      "Monterrey",
      "Parás",
      "Pesquería",
      "Rayones",
      "Sabinas Hidalgo",
      "Salinas Victoria",
      "San Nicolás de los Garza",
      "San Pedro Garza García",
      "Santa Catarina",
      "Santiago",
      "Vallecillo",
      "Villaldama",
    ],
  },

  {
    id: 7,
    state: "Guanajuato",
    image: "/groups/guanajuato.jpg",
    locations: [
      "Moroleón",
      "Jerécuaro",
      "Uriangato",
      "Apaseo el Alto",
      "Romita",
      "Villagrán",
      "Yuriria",
      "Comonfort",
      "Santa Cruz de Juventino Rosas",
      "Purísima del Rincón",
      "San José Iturbide",
      "Abasolo",
      "Salvatierra",
      "Cortazar",
      "Acámbaro",
      "Apaseo el Grande",
      "San Felipe",
      "San Luis de la Paz",
      "San Francisco del Rincón",
      "Valle de Santiago",
      "Pénjamo",
      "Dolores Hidalgo Cuna de la Independencia Nacional",
      "San Miguel de Allende",
      "Guanajuato",
      "Silao de la Victoria",
      "Salamanca",
      "Celaya",
      "Irapuato",
      "León",
    ],
  },
  {
    id: 8,
    state: "Chihuahua",
    image: "/groups/chihuahua.jpg",
    locations: [
      "Ciudad Juárez",
      "Chihuahua",
      "Delicias",
      "Cuauhtémoc",
      "Hidalgo del Parral",
      "Ojinaga",
      "Nuevo Casas Grandes",
      "Camargo",
      "Jiménez",
      "Meoqui",
      "Guerrero",
      "Ascensión",
      "Janos",
      "Galeana",
      "Buenaventura",
      "Ignacio Zaragoza",
      "Praxedis G. Guerrero",
      "Ahumada",
      "Coyame del Sotol",
      "Villa Ahumada",
      "Rosales",
      "Saucillo",
      "Santa Bárbara",
      "Guadalupe",
      "Coronado",
      "Valentín Gómez Farías",
      "San Francisco de Borja",
      "San Francisco de Conchos",
      "Bachíniva",
      "Balleza",
      "Batopilas",
      "Bocoyna",
      "Buenaventura",
      "Camargo",
      "Carichí",
      "Casas Grandes",
      "Coronado",
      "Coyame del Sotol",
      "Cuauhtémoc",
      "Cusihuiriachi",
      "Delicias",
      "Dr. Belisario Domínguez",
      "Galeana",
      "Gómez Farías",
      "Gran Morelos",
      "Guachochi",
      "Guadalupe",
      "Guadalupe y Calvo",
      "Guazapares",
      "Guerrero",
      "Hidalgo del Parral",
      "Ignacio Zaragoza",
      "Janos",
      "Jiménez",
      "Juárez",
      "Julimes",
      "López",
      "Madera",
      "Maguarichi",
      "Manuel Benavides",
      "Matachí",
      "Matamoros",
      "Meoqui",
      "Morelos",
      "Moris",
      "Namiquipa",
      "Nonoava",
      "Nuevo Casas Grandes",
      "Ocampo",
      "Ojinaga",
      "Praxedis G. Guerrero",
    ],
  },
  {
    id: 9,
    state: "Chiapas",
    image: "/groups/chiapas.jpg",
    locations: [
      "Tuxtla Gutiérrez",
      "Tapachula",
      "San Cristóbal de las Casas",
      "Comitán de Domínguez",
      "Palenque",
      "Chiapa de Corzo",
      "Villaflores",
      "Ocosingo",
      "Tonalá",
      "Reforma",
      "Pichucalco",
      "Cintalapa",
      "Huixtla",
      "Motozintla",
      "Las Margaritas",
      "Simojovel",
      "San Fernando",
      "Mapastepec",
      "Berriozábal",
      "Arriaga",
      "Jiquipilas",
      "Suchiapa",
      "Venustiano Carranza",
      "La Trinitaria",
      "Frontera Comalapa",
      "Pijijiapan",
      "Ocozocoautla de Espinosa",
      "Tila",
      "Yajalón",
      "El Bosque",
    ],
  },
  {
    id: 10,
    state: "Oaxaca",
    image: "/groups/oaxaca.jpg",
    locations: [
      "Oaxaca de Juárez",
      "Santa Cruz Xoxocotlán",
      "San Juan Bautista Tuxtepec",
      "Salina Cruz",
      "Juchitán de Zaragoza",
      "Huajuapan de León",
      "San Pedro Mixtepec",
      "San Pedro Pochutla",
      "Santa Lucía del Camino",
      "Loma Bonita",
      "Puerto Escondido",
      "Miahuatlán de Porfirio Díaz",
      "Heroica Ciudad de Tlaxiaco",
      "San Felipe Jalapa de Díaz",
      "Santo Domingo Tehuantepec",
      "San Juan Bautista Valle Nacional",
      "San Pablo Villa de Mitla",
      "Santa María Huatulco",
      "Asunción Nochixtlán",
      "San Pedro Tapanatepec",
      "San Juan Bautista Lo de Soto",
      "San Pedro Jicayán",
      "San Juan Bautista Cuicatlán",
      "San Pedro y San Pablo Ayutla",
      "San Juan Bautista Guelache",
      "San Pedro Amuzgos",
      "San Juan Bautista Jayacatlán",
      "San Pedro Cajonos",
      "San Juan Bautista Tlacoatzintepec",
      "San Pedro Quiatoni",
    ],
  },

  {
    id: 11,
    state: "Guerrero",
    image: "/groups/guerrero.jpg",
    locations: [
      "Acapulco de Juárez",
      "Chilpancingo de los Bravo",
      "Iguala de la Independencia",
      "Zihuatanejo de Azueta",
      "Taxco de Alarcón",
      "Ciudad Altamirano",
      "Chilapa de Álvarez",
      "Tlapa de Comonfort",
      "Ometepec",
      "Coyuca de Benítez",
      "Atoyac de Álvarez",
      "Tecpan de Galeana",
      "San Marcos",
      "Petatlán",
      "Ayutla de los Libres",
      "Tixtla de Guerrero",
      "Pungarabato",
      "Arcelia",
      "Igualapa",
      "Xochistlahuaca",
      "San Luis Acatlán",
      "Marquelia",
      "Copala",
      "Cuautepec",
      "Florencio Villarreal",
      "Cuajinicuilapa",
      "Tecoanapa",
      "Metlatónoc",
      "Alcozauca de Guerrero",
      "Atlixtac",
      "Malinaltepec",
      "Tlacoapa",
      "Xalpatláhuac",
      "Zapotitlán Tablas",
      "Acatepec",
      "Atlamajalcingo del Monte",
      "Cochoapa el Grande",
      "Iliatenco",
      "José Joaquín de Herrera",
      "Alpoyeca",
      "Cualác",
      "Huamuxtitlán",
      "Olinalá",
      "Xochihuehuetlán",
      "Zitlala",
      "Ahuacuotzingo",
      "Mochitlán",
      "Quechultenango",
      "Eduardo Neri",
      "Juan R. Escudero",
      "Tecoanapa",
      "Tepecoacuilco de Trujano",
      "Huitzuco de los Figueroa",
      "Pilcaya",
      "Tetipac",
      "Apaxtla",
      "Canuto A. Neri",
      "Cuetzala del Progreso",
      "General Canuto A. Neri",
      "Ixcateopan de Cuauhtémoc",
      "Pedro Ascencio Alquisiras",
      "Teloloapan",
      "Cocula",
      "Copalillo",
      "Cualac",
      "Huamuxtitlán",
      "Olinalá",
      "Xochihuehuetlán",
      "Zitlala",
      "Ahuacuotzingo",
      "Mochitlán",
    ],
  },
  {
    id: 12,
    state: "Baja California",
    image: "/groups/bajacalifornia.jpg",
    locations: [
      "Tijuana",
      "Mexicali",
      "Ensenada",
      "Playas de Rosarito",
      "Tecate",
      "San Quintín",
      "San Felipe",
      "San Luis Río Colorado",
      "Puerto Peñasco",
      "González Ortega",
      "El Porvenir",
      "El Sauzal",
      "El Rosario",
      "El Pípila",
      "El Papalote",
      "El Nido",
      "El Mirador",
      "El Mármol",
      "El Manantial",
      "El Lienzo",
      "El Hongo",
      "El Florido",
      "El Descanso",
      "El Centinela",
      "El Choropo",
      "El Chorro",
      "El Choyal",
      "El Ciprés",
      "El Chaparral",
      "El Carrizo",
      "El Cajón",
      "El Borrego",
      "El Águila",
      "El Aguajito",
      "El Aguaje",
      "El Álamo",
    ],
  },
  {
    id: 13,
    state: "Tamaulipas",
    image: "/groups/tamaulipas.jpg",
    locations: [
      "Reynosa",
      "Matamoros",
      "Nuevo Laredo",
      "Ciudad Victoria",
      "Tampico",
      "Ciudad Madero",
      "Altamira",
      "Ciudad Mante",
      "San Fernando",
      "Río Bravo",
      "Valle Hermoso",
      "Miguel Alemán",
      "Gustavo Díaz Ordaz",
      "Camargo",
      "Reynosa Díaz",
      "Hidalgo",
      "Padilla",
      "San Carlos",
      "San Nicolás",
      "Villagrán",
      "Mainero",
      "Abasolo",
      "Jiménez",
      "Llera",
      "González",
      "Xicoténcatl",
      "Ocampo",
      "Antiguo Morelos",
      "Nuevo Morelos",
      "El Mante",
    ],
  },
  {
    id: 14,
    state: "Michoacán",
    image: "/groups/michoacan.jpg",
    locations: [
      "Morelia",
      "Uruapan",
      "Zamora",
      "Lázaro Cárdenas",
      "Apatzingán",
      "Zitácuaro",
      "La Piedad",
      "Pátzcuaro",
      "Hidalgo",
      "Jacona",
      "Sahuayo",
      "Los Reyes",
      "Maravatío",
      "Puruándiro",
      "Ciudad Hidalgo",
      "Tacámbaro",
      "Zinapécuaro",
      "Tingüindín",
      "Tuxpan",
      "Taretan",
      "Tingambato",
      "Tzintzuntzan",
      "Quiroga",
      "Paracho",
      "Ario de Rosales",
      "Coalcomán",
      "Huetamo",
      "Jiquilpan",
      "Múgica",
      "Nuevo Parangaricutiro",
    ],
  },
  {
    id: 15,
    state: "Sinaloa",
    image: "/groups/sinaloa.jpg",
    locations: [
      "Culiacán",
      "Mazatlán",
      "Los Mochis",
      "Guasave",
      "Navolato",
      "Escuinapa",
      "El Rosario",
      "El Fuerte",
      "Salvador Alvarado",
      "Mocorito",
      "Angostura",
      "Badiraguato",
      "Choix",
      "Concordia",
      "Cosalá",
      "San Ignacio",
      "Sinaloa de Leyva",
    ],
  },
];
